version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run format:check
      - run: npm run lint
      - run: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
