version: 2.1

supported-eslint-versions: &supported-eslint-versions ["local"]

jobs:
  build:
    parameters:
      eslint-version:
        type: string
        description: >
          Overrides the installed version of ESLint. When set to "local" the version of ESLint set
          frozen in the package-lock.json is used.
        default: "local"
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - when:
          condition:
            not:
              equal: [<<parameters.eslint-version>>, "local"]
          steps:
            - run:
                name: Override version of eslint@<<parameters.eslint-version>>
                command: npm install --save-dev eslint@<<parameters.eslint-version>>

      - run: npm run format:check
      - run: npm run lint
      - run: npm run test

workflows:
  build_and_test:
    jobs:
      - build:
          matrix:
            parameters:
              eslint-version: *supported-eslint-versions
