const auraApiRule = require('./rules/aura-api');

const rules = {
  'aura-api': {
    create: auraApiRule
  }
};

const ERROR = 2;
const WARNING = 1;
const IGNORE = 0;

module.exports = {
  rules,
  configs: {
    recommended: {
      plugins: [
        'eslint-plugin-aura'
      ],
      env: {
        browser: true,
        es6: false
      },
      parserOptions: {
        ecmaVersion: 5
      },
      globals: {
        $A: true,
        AuraContext: true,
        AuraSerializationService: true,
        AuraExpressionService: true,
        AuraEventService: true,
        AuraLocalizationService: true,
        AuraStorageService: true,
        AuraStyleService: true,
        MetricsService: true,
        AuraDevToolService: true,
        Component: true,
        CKEDITOR: true,
        FORCE: true,
        moment: true,
        exports: true,
        iScroll: true,
        unescape: true,
        Promise: true,
        Fixture: 'readonly',
        ScrumTeam: 'readonly',
        ImportJson: 'readonly',
        Test: 'readonly',
        Fact: 'readonly',
        Data: 'readonly',
        Async: 'readonly',
        Skip: 'readonly',
        Records: 'readonly',
        Stubs: 'readonly',
        Mocks: 'readonly',
        Assert: 'readonly'
      },
      rules: {
        // custom rules
        'aura/aura-api': ERROR,

        // platform rules that as immutable
        'no-alert': ERROR,
        'no-array-constructor': ERROR, // help with instanceof
        'no-bitwise': WARNING, // usually a typo | -> ||
        'no-caller': ERROR, // strict mode compliance
        'no-catch-shadow': ERROR,
        'no-cond-assign': ERROR,
        'no-console': ERROR,
        'no-constant-condition': ERROR,
        'no-control-regex': WARNING,
        'no-debugger': ERROR,
        'no-delete-var': WARNING, // for perf reasons, we might want to set this to 2
        'no-div-regex': WARNING,
        'no-dupe-keys': ERROR,
        'no-dupe-args': ERROR,
        'no-duplicate-case': ERROR,
        'no-else-return': IGNORE,
        'no-empty-character-class': ERROR,
        'no-eq-null': WARNING,
        'no-eval': ERROR,
        'no-ex-assign': ERROR,
        'no-extend-native': ERROR,
        'no-extra-bind': ERROR,
        'no-extra-boolean-cast': ERROR,
        'no-fallthrough': ERROR, // switch fallthrough
        'no-floating-decimal': WARNING, // var num = .5;
        'no-func-assign': ERROR,
        'no-implied-eval': ERROR,
        'no-inner-declarations': [ERROR, 'functions'],
        'no-invalid-regexp': ERROR,
        'no-irregular-whitespace': ERROR,
        'no-iterator': ERROR,
        'no-label-var': ERROR,
        'no-labels': ERROR,
        'no-loop-func': ERROR,
        'no-multi-str': ERROR,
        'no-native-reassign': ERROR,
        'no-negated-in-lhs': ERROR,
        'no-nested-ternary': WARNING,
        'no-new': ERROR,
        'no-new-func': ERROR,
        'no-new-object': ERROR,
        'no-new-wrappers': ERROR,
        'no-obj-calls': ERROR,
        'no-octal': ERROR,
        'no-octal-escape': ERROR,
        'no-param-reassign': WARNING,
        'no-plusplus': [
          'error',
          { allowForLoopAfterthoughts: true }
        ],
        'no-proto': ERROR,
        'no-redeclare': ERROR,
        'no-regex-spaces': ERROR,
        'no-return-assign': ERROR,
        'no-script-url': ERROR,
        'no-self-compare': ERROR,
        'no-sequences': ERROR, // var a = (3, 5);
        'no-shadow': ERROR,
        'no-shadow-restricted-names': ERROR,
        'no-sparse-arrays': ERROR,
        'no-ternary': IGNORE,
        'no-throw-literal': WARNING,
        'no-undef': WARNING,
        'no-undef-init': WARNING,
        'no-undefined': IGNORE,
        'no-underscore-dangle': IGNORE,
        'no-unreachable': ERROR,
        'no-unused-expressions': WARNING,
        'no-unused-vars': [WARNING, { vars: 'all', args: 'after-used' }],
        'no-use-before-define': [ERROR, { functions: false }],
        'no-void': ERROR,
        'no-var': IGNORE,
        'no-with': ERROR,
        'consistent-return': WARNING,
        'default-case': ERROR,
        'dot-notation': [WARNING, { allowKeywords: true }],
        eqeqeq: ['error', 'smart'],
        'guard-for-in': WARNING,
        'handle-callback-err': WARNING,
        'new-parens': ERROR,
        radix: ERROR,
        strict: IGNORE,
        'use-isnan': ERROR,
        'valid-typeof': ERROR,
        'wrap-iife': [WARNING, 'any'],
        'no-trailing-spaces': 1,
        'no-spaced-func': 1,
        'no-mixed-spaces-and-tabs': 0,
        'no-multi-spaces': 0,
        'no-multiple-empty-lines': 0,
        'no-lone-blocks': 1,
        'no-lonely-if': 1,
        'no-inline-comments': 0,
        'no-extra-parens': 0,
        'no-extra-semi': 1,
        'no-warning-comments': [0, { terms: ['todo', 'fixme', 'xxx'], location: 'start' }],
        'block-scoped-var': 1,
        'brace-style': [1, '1tbs'],
        camelcase: 1,
        'comma-dangle': [1, 'never'],
        'comma-spacing': 1,
        'comma-style': 1,
        complexity: [0, 11],
        'consistent-this': [0, 'that'],
        curly: [1, 'all'],
        'eol-last': 0,
        'func-names': 0,
        'func-style': [0, 'declaration'],
        'generator-star-spacing': 0,
        indent: 0,
        'key-spacing': 0,
        'keyword-spacing': [0],
        'max-depth': [0, 4],
        'max-len': [0, 80, 4],
        'max-nested-callbacks': [0, 2],
        'max-params': [0, 3],
        'max-statements': [0, 10],
        'new-cap': 0,
        'newline-after-var': 0,
        'one-var': [0, 'never'],
        'operator-assignment': [0, 'always'],
        'padded-blocks': 0,
        'quote-props': 0,
        quotes: 0,
        semi: 1,
        'semi-spacing': [0, { before: false, after: true }],
        'sort-vars': 0,
        'space-after-function-name': [0, 'never'],
        'space-before-blocks': [0, 'always'],
        'space-before-function-paren': [0, 'always'],
        'space-before-function-parentheses': [0, 'always'],
        'space-in-brackets': [0, 'never'],
        'space-in-parens': [0, 'never'],
        'space-infix-ops': 0,
        'space-unary-ops': [1, { words: true, nonwords: false }],
        'spaced-comment': [0, 'always'],
        'vars-on-top': 0,
        'valid-jsdoc': 0,
        'wrap-regex': 0,
        yoda: [1, 'never']
      },
    }
  }
};
